[workspace]
members = [
    ".",
]

[package]
name = "sea-orm"
version = "0.1.0"
authors = [ "Chris Tsang <tyt2y7@gmail.com>" ]
edition = "2018"
description = "A database agnostic ORM for Rust"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/sea-orm"
repository = "https://github.com/SeaQL/sea-orm"
categories = [ "database" ]
keywords = [ "orm", "database", "sql", "mysql", "postgres", "sqlite" ]
publish = false

[lib]
name = "sea_orm"
path = "src/lib.rs"

[dependencies]
async-trait = "^0.1"
async-std = { version = "^1.9", features = [ "attributes" ] }
futures = { version = "^0.3" }
sea-query = { version = "^0.10", features = [ "sqlx-mysql" ] }
# sea-schema = { path = "../sea-schema" }
serde = { version = "^1.0", features = [ "derive" ] }
sqlx = { version = "^0.5", features = [ "runtime-async-std-native-tls", "mysql", "any", "chrono", "time", "bigdecimal", "decimal", "uuid", "json" ] }
strum = { version = "^0.20", features = [ "derive" ] }
