blank_issues_enabled: true
contact_links:
  - name: Ask a question or look for help
    url: https://github.com/SeaQL/sea-orm/discussions/new?category=q-a
    about: Please try to provide sufficient context, snippets to reproduce and error messages (if any).
  - name: SeaQL Discord Server
    url: https://discord.com/invite/uCPdDXzbdv
    about: Join our Discord server to chat with others in the SeaQL community!