[package]
name = "sea-orm-rocket-example"
version = "0.1.0"
authors = ["Sam Samai <sam@studio2pi.com.au>"]
edition = "2018"
publish = false

[workspace]

[dependencies]
async-stream = { version = "^0.3" }
async-trait = { version = "0.1" }
futures = { version = "^0.3" }
futures-util = { version = "^0.3" }
actix-http = "2"
actix-web = "3"
tera = "1.8.0"

# remove `path = ""` in your own project
sea-orm = { path = "../../", version = "^0.2", features = [
  "macros",
  "sqlx-all",
  "runtime-tokio-native-tls",
], default-features = false }
serde_json = { version = "^1" }

[dependencies.sqlx]
version = "^0.5"
default-features = false
features = ["macros", "offline", "migrate"]

[features]
default = ["sqlx-postgres"]
sqlx-mysql = ["sea-orm/sqlx-mysql"]
sqlx-postgres = ["sea-orm/sqlx-postgres"]
